blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/Z8Ae5H5DjZ
    about: Ask questions and discuss with other helldivers.
  - name: Donate through ko-fi
    url: https://ko-fi.com/galacticwideweb
    about: If you want to support the development, check out ko-fi