name: "\U0001F41E Localization"
description: Request a language or assist with translations
title: "[LOCALIZATION]: "
labels: ["localization"]
body:
  - type: markdown
    attributes:
      value: |
        **This form is only for submitting translation requests or assisting in translations.**
  - type: dropdown
    id: language
    attributes:
      label: The language
      description: |
        The language that this request is about
      options:
        - English
        - Deutsch
        - Español
        - Français 
        - Italiano
        - 日本語
        - 한국어
        - بهاس ملايو
        - Polski
        - Português
        - Русский язык
        - 简体中文
    validations:
      required: true
  - type: dropdown
    id: help-translate
    attributes:
      label: Can you help with translation?
      description: |
        If this language is chosen to be added to the bot, would you be able to assist with translation?
        This will likely include editing a JSON file with template text.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?